image: kasproject/kas-isar:2.2

variables:
  GIT_STRATEGY: clone
  release: buster
  extention: base
  use_rt: enable
  targz: enable
  dtb: none
  deploy: enable

stages:
  - build
  - cve-check

default:
  before_script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

.build_base:
  stage: build
  variables:
    base_yaml: "kas-cip.yml:kas/board/${target}.yml"
    dpkg_status: "cip-core-image-1.0-r0.dpkg_status"
  script:
    - sudo rm -rf build/tmp
    - if [ "${use_rt}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/rt.yml"; fi;
    - if [ "${extention}" != "base" ]; then base_yaml="${base_yaml}:kas/opt/${extention}.yml"; fi;
    - if [ "${targz}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/targz-img.yml"; fi;
    - kas build ${base_yaml}
    - if [ "${deploy}" = "enable" ]; then scripts/deploy-cip-core.sh ${release} ${target} ${extention} ${dtb} ${dpkg_status}; fi
  except:
    - schedules

cve-checks:
  stage: cve-check
  image: registry.gitlab.com/cip-playground/cip-core-sec:build-latest
  script:
    - apt update
    - apt install -y python3-pip
    - scripts/run-cve-checks.sh

# base image
build:simatic-ipc227e-base:
  extends:
    - .build_base
  variables:
    target: simatic-ipc227e

build:bbb-base:
  extends:
    - .build_base
  variables:
    target: bbb
    dtb: am335x-boneblack.dtb

build:iwg20m-base:
  extends:
    - .build_base
  variables:
    target: iwg20m
    dtb: r8a7743-iwg20d-q7-dbcm-ca.dtb

build:hihope-rzg2m-base:
  extends:
    - .build_base
  variables:
    target: hihope-rzg2m
    dtb: renesas/r8a774a1-hihope-rzg2m-ex.dtb

build:qemu-amd64-base:
  extends:
    - .build_base
  variables:
    target: qemu-amd64
    extention: security
    dpkg_status: cip-core-image-security-1.0-r0.dpkg_status
    use_rt: disable
    targz: disable
    deploy: disable

# test
build:simatic-ipc227e-test:
  extends:
    - .build_base
  variables:
    target: simatic-ipc227e
    extention: test

build:bbb-test:
  extends:
    - .build_base
  variables:
    target: bbb
    extention: test
    dtb: am335x-boneblack.dtb

build:iwg20m-test:
  extends:
    - .build_base
  variables:
    target: iwg20m
    extention: test
    dtb: r8a7743-iwg20d-q7-dbcm-ca.dtb

build:hihope-rzg2m-test:
  extends:
    - .build_base
  variables:
    target: hihope-rzg2m
    extention: test
    dtb: renesas/r8a774a1-hihope-rzg2m-ex.dtb
