image: kasproject/kas-isar:1.1

variables:
  GIT_STRATEGY: clone

all:
  stage: build
  script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

    - kas build kas.yml:board-simatic-ipc227e.yml:opt-rt.yml:opt-targz-img.yml
    - scripts/deploy-cip-core.sh buster simatic-ipc227e

    - sudo rm -rf build/tmp
    - kas build kas.yml:board-bbb.yml:opt-rt.yml:opt-targz-img.yml
    - scripts/deploy-cip-core.sh buster bbb am335x-boneblack.dtb

    - sudo rm -rf build/tmp
    - kas build kas.yml:board-iwg20m.yml:opt-rt.yml:opt-targz-img.yml
    - scripts/deploy-cip-core.sh buster iwg20m r8a7743-iwg20d-q7-dbcm-ca.dtb

    - sudo rm -rf build/tmp
    - kas build kas.yml:board-rzg2m.yml:opt-rt.yml:opt-targz-img.yml
    - scripts/deploy-cip-core.sh buster hihope-rzg2m r8a774a1-hihope-rzg2m-ex.dtb
